image: python:3.11

stages:
  - build
  - release

test:
  variables:
    PRE_COMMIT_HOME: "$CI_PROJECT_DIR/.cache/pre-commit"
    PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .cache/pre-commit
      - .cache/pip
      - venv
  stage: build
  before_script:
    - pip install virtualenv poetry pre-commit urllib3==1.26.15
    - virtualenv venv
    - source venv/bin/activate
    - poetry config virtualenvs.create false
    - poetry install --no-root
  script:
    - pre-commit run -a --hook-stage manual
    - pytest

pypi:
  variables:
    TWINE_USERNAME: "__token__"
  stage: release
  needs: [test]
  rules:
  - if: $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+$/
    when: on_success
  script:
      - pip install -U twine gitchangelog pystache poetry
      - gitchangelog
      - poetry build
      - twine upload dist/*
